# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/oneplus/hotdog/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifeq ($(TARGET_DEVICE),hotdog)
$(call add-radio-file-sha1-checked,radio/LOGO.img,a5c74a189ab7550cc881bb4bdc47c80f761c8a41)
$(call add-radio-file-sha1-checked,radio/abl.img,f57a7de894accd2de0e6305191345c5651808683)
$(call add-radio-file-sha1-checked,radio/aop.img,de50ed5a241404dd70b8fdb8e85b316646711168)
$(call add-radio-file-sha1-checked,radio/bluetooth.img,d18e0afc9cddba16540440373c595235a7de2d57)
$(call add-radio-file-sha1-checked,radio/cmnlib.img,60fbb72efd280cee950799da3aa5665503a76ab2)
$(call add-radio-file-sha1-checked,radio/cmnlib64.img,d1d5ea79e6af41dda687757a02c5a4edc962fecd)
$(call add-radio-file-sha1-checked,radio/devcfg.img,c2298c537645e9e7a80efae19130a61f566a6608)
$(call add-radio-file-sha1-checked,radio/dsp.img,dfb074425e9778b1b0dc47db897ea8c4c6e8e4cc)
$(call add-radio-file-sha1-checked,radio/hyp.img,67710429bffd10e68ae12847b0038062f7336b05)
$(call add-radio-file-sha1-checked,radio/imagefv.img,7baccaf52f56c9b46d1c66fcbbef3bfb4add3074)
$(call add-radio-file-sha1-checked,radio/keymaster.img,f9c8bf0f1454b09a52b917f521f6bfbf2a7c7fa5)
$(call add-radio-file-sha1-checked,radio/modem.img,cfd352210fe56384702d0f789a3da0517fe3b19e)
$(call add-radio-file-sha1-checked,radio/multiimgoem.img,9fb1c8322f0a01d4220ac1a9e79345554706cc8b)
$(call add-radio-file-sha1-checked,radio/qupfw.img,0745b63ce26326b3a2b0bb8181ec76c0699d14e6)
$(call add-radio-file-sha1-checked,radio/storsec.img,3bf6d385b57789a9cfa185ef6a07dbb2bcef7a31)
$(call add-radio-file-sha1-checked,radio/tz.img,9c217aa89088562439cce3ea1c5899bd18eaecf4)
$(call add-radio-file-sha1-checked,radio/uefisecapp.img,e25feb3f2003ceebfb9dcffd3d4d1aeaf01ee8a9)
$(call add-radio-file-sha1-checked,radio/xbl.img,0e69cb18f029141ae306e3faeaaa286854d3acbc)
$(call add-radio-file-sha1-checked,radio/xbl_config.img,a1fc644ccaf662249c533b879a1988c67ff624c5)
endif
